### ISSUE TITLE
Remove wtfnode

### ISSUE THREAD

**Issue by RobLoach** [ForbesLindesay/testit#20]
WTF we use it for?

**Comment by RobLoach** [comment]
Can sometimes get.....
```
Module parse failed: node_modules/wtfnode/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 
| 'use strict';
 @ ../~/testit/index.js 6:16-30
 @ ./test.js
```

**Comment by ForbesLindesay** [comment]
It's pretty useful when running node tests.  It tells you what is keeping a process alive - i.e. open network connections, timeouts etc.

I find it pretty useful to make sure we don't leak these in node.  I would happily accept a pull request that helps ensure it doesn't get loaded by browser based tests though.

**Comment by RobLoach** [comment]
Fixed the issue in wtfnode. We just have to update it. Thanks!
